# Generated by Django 4.1.5 on 2023-01-13 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('no_idea', '0002_alter_art_gallery_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art_gallery',
            name='user',
            field=models.ForeignKey(blank=True, default=1832501751920, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
