# Generated by Django 4.1.5 on 2023-01-18 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='art_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.TextField(max_length=80)),
                ('desc_of_art', models.TextField(max_length=100000)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(max_length=10000)),
                ('user', models.ForeignKey(blank=True, default=1948776341744, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
